<?php

drupal_add_js(drupal_get_path('module', 'communism') . '/js/communism.js', array('type' => 'file', 'scope' => 'footer'));
drupal_add_css(drupal_get_path('module', 'communism') . '/css/communism.css', array('group' => CSS_DEFAULT, 'type' => 'file'));

function communism_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  if($form_id == "ad_campaign_node_form"){
    unset($form['actions']['preview']);
    unset($form['options']['promote']);
    unset($form['options']['sticky']);
    unset($form['comment_settings']);
    unset($form['revision_information']);
    unset($form['#metatags']);
    $form['#groups']['group_web']->label = "";
    $form['#groups']['group_facebook']->label = "";
    $form['field_web_ad_landing_page']['#suffix'] = "<div class='edit-field-web-ad-landing-page-und-0-value-msg'></div>";
    $form['field_facebook_ad_landing_page']['#suffix'] = "<div class='edit-field-facebook-ad-landing-page-und-0-value-msg'></div>";
  } else if($form_id == "user_profile_form") {
    unset($form['#metatags']);
  }
}

function _communism_fetch_landing_url($url){
  $result = drupal_http_request(urldecode($url));
  if($result->code != 200){
    watchdog("communism", "URL test of ".urldecode($url)." returned ".$result->code."\n<pre>\n".print_r($result, true)."</pre>");
    header("HTTP/1.1 403 ", true, 403);
  } else {
    print $result->data;
  }
}

function communism_menu() {
  $items = array();
  $items['fetch-landing-url'] = array(
    'title' => "Fetch a landing URL and test for the presence of Adroll's JS",
    'page callback' => '_communism_fetch_landing_url',
    'page arguments' => array(1),
    'access arguments' => array("create ad_campaign content"),
    'type' => MENU_CALLBACK
  );
	return($items);
}
